#to run: docker-compose up -d

version: "2"
services:
  tad:
    image: postgres:13.4
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=olisaude
      - TZ=GMT
    ports:
      - 5432:5432
  pgadmi:
    container_name: pgadmi
    image: dpage/pgadmin4
    ports:
       - "9080:80"
    environment:
       - "PGADMIN_DEFAULT_EMAIL=olisaude@olisaude.com.br"
       - "PGADMIN_DEFAULT_PASSWORD=olisaude"